# Terminal

# True Color
set-option -sa terminal-overrides ",xterm*:Tc"

# Mouse support
set -g mouse on


# Prefix

unbind C-b

set -g prefix C-Space
bind C-Space send-prefix


# Navigation

# Alt+h / Alt+l para trocar de janela
bind -n M-H previous-window
bind -n M-L next-window


# Window & Pane Indexes

# Começar contagem em 1
set -g base-index 1
set -g pane-base-index 1

# Renumerar automaticamente após fechar janelas
set -g renumber-windows on


# Copy Mode (Vim)

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Activity Monitoring

setw -g monitor-activity on
set -g visual-activity on


# Status Bar

# Centralizar lista de janelas
set -g status-justify centre


# Theme

set -g @tmux-gruvbox 'dark'


# Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Restore de sessões Vim/Neovim
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# Continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# TPM
run '~/.tmux/plugins/tpm/tpm'
