require "nvchad.mappings"

require "mappings.general"
require "mappings.tmux"
require "mappings.lsp"
require "mappings.git"
require "mappings.ufo"
require "mappings.dropbar"
require "mappings.trouble"
require "mappings.daps"
